version: '3.8'
services:
  api:
    build:
      context: .
      target: dev
    image: quizapp-api:dev
    ports:
      - "31000:8080"
      - "9229:9229"
    environment:
      JWT_SECRET: aGVsbG93b3JsZAo=
      DB_URL: mongodb://mongo:27017
    depends_on:
      - mongo
  mongo:
    image: mongo
    logging:
      driver: "none"
