version: '3.8'
services:
  web:
    build: ./client
    image: quizapp-web:dev
    ports:
      -  "80:80"
  api:
    build: .
    image: quizapp-api:dev
    ports:
      - "31000:8080"
    env_file:
      - .env
  mongodb:
    image: mongo
